== References
The following normative documents contain provisions that, through reference in this text, constitute provisions of this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.

Adobe development association. TIFF Revision 6.0 Final — June 3, (1992) https://www.adobe.io/content/dam/udp/en/open/standards/tiff/TIFF6.pdf


[NOTE]
====
Insert References here. If there are no references, state “There are no normative references”.

References are to follow the Springer LNCS style, with the exception that optional information may be appended to references: DOIs are added after the date and web resource references may include an access date at the end of the reference in parentheses. See examples from Springer and OGC below.

Smith, T.F., Waterman, M.S.: Identification of Common Molecular Subsequences.
J. Mol. Biol. 147, 195–197 (1981)

====
