[[GeoTIFFFormatRequirements]]
== GeoTIFF format requirements
A COG file is a file that conforms to a subset of the TIFF specification (or the BigTIFF specification) and adheres to the GeoTIFF tag requirements. A COG uses two main organization techniques available in the TIFF version 6.0 specification:
Tiling and Reduced-Resolution Subfiles (sometimes called _Overviews_).
The tiled data can also be compressed for more efficient passage online.
In addition, a COG file uses the GeoTIFF conventions for storing the relevant geospatial metadata. For convenience, Tiling and Reduced-Resolution Subfiles are presented in two independent conformance classes.

[[geotiff-format-requirements-class]]
=== Requirement Class GeoTIFF Tiles
include::requirements/requirements_geotiff_format.adoc[]

==== Basic format
A COG file is a TIFF or a BigTiFF file.
include::requirements/geotiff_format/basic_format.adoc[]

include::recommendations/geotiff_format/basic_format.adoc[]

==== Tiles
In the context for a TIFF file, *Tiling* is a strategy for dividing the content in the TIFF file differently than using the classical _Strips_. In the _Strips_ approach the data are organized into sequences of lines (rows) while *tiling* creates a number of internal rectangular _tiles_ stored in the actual image. _Strips_ divide the content of an image vertically (rows) but not horizontally (columns). With _Tiling_, a much quicker access to a certain area or two dimensional bounding box is possible as the relevant data is closer in the file and the portion of bytes that needs to be read is smaller than in the _strips_ approach.

include::requirements/geotiff_format/tiling.adoc[]

NOTE: The ability to have multiple Image File Directories (IFD) becomes important when the COG has also _overviews_. See the next requirements class for more details.

Tiles, as defined in the TIFF version 6.0 specification, can be mapped to the ones defined in the OGC Two Dimensional Tile Matrix Set Standard (2D-TMS).
For example in 2D-TMS, the TIFF 6.0 forces all tiles to be of the same size.
This is possible with the introduction of the concept of padding:
If necessary extra blank rows or columns are added to the right-most and bottom-most tile to make them the same shape as other tiles.
However, the naming of the TIFF tags used version 6.0 and the property names used in the 2D-TMS differ.
The following table provides a mapping between the two standards.

[#mapping-tiff-and-2d-tms,reftext='{table-caption} {couner:table-num}']
.Mapping between the OGC the 2D-TMS standard and the TIFF version 6.0, section 15
[width = "100%",options="header"]
|===
| OGC 2D-TMS | TIFF v. 6.0 | Definition
| TileWidth | TileWidth | The tile width in pixels. The number of columns in each tile
| TileHeight | TileLength | The tile height in pixels. The number of rows in each tile
| MatrixWidth | TilesAcross | Number of tiles in the width direction
| MatrixHeight | TilesDown | Number of tiles in the height direction
|===

Please note that the TIFF 6.0 specification
imposes the requirement that _TileWidth and TileLength must be a multiple of 16_.
The specification argues that this restriction improves performance in some graphics environments
and enhances compatibility with compression schemes such as JPEG.
There is no such restriction in the OGC 2D-TMS.

==== Compression
Compression of the bytes is a general best practice for enabling software
to quickly access data, in particular over the network.
The combination of compression with the HTTP GET Range requests maximizes efficiency.
HTTP GET Range will be standardized in another requirements class.

include::recommendations/geotiff_format/recommendation_compression.adoc[]

==== Planar Configuration considerations

When more than one component is encoded in a TIFF file, the TIFF provides two possibilities:

* The component values for each pixel are stored contiguously. This is marked in the file as PlanarConfiguration=Contig (a.k.a. Chunky format, value 1). This is a common arrangement for RGB combinations of bands. The data is stored as RGBRGBRGB… (this arrangement is also known as Band Interleaved by Pixel, BIP)
* The components are stored in separate _component planes_. This is marked in the file as PlanarConfiguration=Separate (a.k.a. Planar format, value 2). This is the common arrangement for the bands of a multispectral image (this arrangement is also known as Band Sequential, BSQ).

NOTE: (extracted from the TIFF 6.0 specification) PlanarConfiguration=2 is not currently [written in 1992] in widespread use and it is not recommended for general interchange.

Following this note, most common implementations of the COG encoders (e.g. GDAL) use PlanarConfiguration=1 (see https://gdal.org/drivers/raster/cog.html#high-level).

[[geotiff-overviews-requirements-class]]
=== Requirement Class GeoTIFF Overviews

include::requirements/requirements_geotiff_overviews.adoc[]

==== Requirement Reduced-Resolution Subfiles
*Reduced-Resolution Subfiles* (a.k.a _Overviews_) are down sampled versions of the same image included in the same TIFF file. This means that an overview is a _zoomed out_ version from the original image. It has less detail but is also smaller. For visualization purposes or for analytical processes that do not require full resolution, a COG can provide _Reduced-Resolution Subfiles_ that match different scale denominators or cell sizes required by clients. _Reduced-Resolution Subfiles_ increase the size of the file but also increase performance.

NOTE: The general description of the COG use the concept of _overviews_. Actually,
there is nothing called _overviews_ in the TIFF version 6.0 specification.
Instead, the TIFF version 6.0 describes how a TIFF file can be composed of one or more images, each one stored in
an Image File Directories (IFD). Some IFDs may contain reduced-resolution subfiles.
This is the reason why this standard favors the use of the expression _Reduced-Resolution Subfiles_ to talk about _overviews_.

There may be more than one IFD in a TIFF file and each IFD indicates
the offset of the next IFD sits in the file (or 0 if no other IFD is available).
Each IFD defines a subfile. Having images as subfiles has several applications.
The NewSubfileType entry specifies several types of subfiles, among which we distinguish:
- IFD with a NewSubfileType tag whose bit 0 is *not* set, or without a NewSubfileType tag, to mean a _full-resolution image data_
- IFD with a NewSubfileType tag whose bit 0 is set, to mean a _reduced-resolution image data of the full resolution one_.

include::requirements/geotiff_overviews/overviews.adoc[]

NOTE: The presence of _reduced-resolution subfiles_ in a COG file is optional. Only the COG files that conform to this conformance class are forced to have _reduced-resolution subfiles_.

The TIFF spec is very flexible with how IFDs are positioned in the file; the only requirement is that the last 4 bytes of the IFD point to the byte offset of the next. So a totally valid TIFF could contain an optimized image where the full resolution image IFD is at the start of the file, the IFD of the first overview is at the end of the file, and the IFD of the second overview is at the middle of the file. Reading the header of an TIFF like this would require making three consecutive requests.

To increase performance, the IFD should be arranged in a particular order expressed in the following recommendation. In the following recommendation, the "order" implies both the order of the IFD links as well as the position in the file implied by the offset.

The advantage of this IFD order is allowing readers to fetch the entire TIFF header (including all IFDs for all subfiles) in a single request upon opening the file for the first time. This reduces the number of file accesses needed to read it and improves cache-ability of the TIFF header for repeat requests to the same image.

For example, when the file is accessed by HTTP range, available from a S3 backed, the latency per HTTP request is about ~20-30ms that will be added other latencies due to data locality and internet transfer (~150ms is a common value). Fetching the header of a COG over 3 consecutive HTTP requests adds ~540ms of latency which is large enough to be perceived by the user, giving a feeling of slow/clunky display especially if rendered in a web browser. Minimizing the number of requests needed to read a COG file is more important over slow internet connections where latencies are exacerbated.

include::recommendations/geotiff_overviews/ifd_order.adoc[]

NOTE: There can be more than one full-resolution image data in the file. In this case, each full-resolution image data will be contiguous to its _reduced-resolution subfiles_ and their IFDs.

[[geotiff-keys-requirements-class]]
=== Requirement Class GeoTIFF Keys
The GeoTIFF standard defines a mechanism to add GeoTIFF keys to a TIFF file.
The main purpose of these keys is to add a geospatial reference to the data stored in the TIFF file. In a COG, GeoTIFF keys are a fundamental part of the standard as most of the COG files are geospatially referenced TIFFs.

include::requirements/requirements_geotiff_keys.adoc[]

==== Requirement GeoTIFF
A COG uses GeoTIFF to document the metadata about the TIFF file, including the georeference of the full resolution images IFDs. The georeference of the Reduced-Resolution Subfiles is derived from the georeference of the full resolution images IFDs.

include::requirements/geotiff_keys/basic_metadata_format.adoc[]

The OGC-NA maintains a register of TIFF tags relevant for the geospatial community (most of them defined in the GeoTIFF standard) with the URL http://www.opengis.net/def/geotiff-tag. The COG standard does neither defines COG specific TIFF tags nor GeoTIFF keys. In the future it may be necessary for the communities that use COG to register tags for their specialist use cases. It is also possible that they reuse the existing GeoTIFF tags to define new GeoTIFF keys. Such tags or keys could then be organized into groups that deal with the needs of a particular domain.

==== Requirement Georeference Keys
There is a geometrical relation between the reduced-resolution subfiles and the corresponding full-resolution subfile. Only full-resolution subfiles are required to have GeoTIFF keys.

include::requirements/geotiff_keys/keys_georeference.adoc[]

All linked reduced-resolution subfiles (a.k.a IFDs whose bit 0 of the value of the NewSubfileType tag is set) that are linked
to a full resolution IFD (i.e. an IFD whose bit 0 of the value of the NewSubfileType tag is *not* set, or NewSubfileType absent) share the set of georeference keys from the full resolution IFD. In practice this means that they have a common CRS and extent information, and differ only by their resolution.
This means that there is the assumption that all related subfiles share the same point of origin for the top left corner or the image.

include::requirements/geotiff_keys/point-of-origin.adoc[]

The pixel size in the first dimension of a reduced-resolution subfile can be calculated by multiplying the full-resolution subfile pixel size by the ImageWidth ratio between the full-resolution and the reduced-resolution.
The pixel size in the second dimension of a reduced-resolution subfile can be calculated by multiplying the full-resolution subfile pixel size by the ImageHeight ratio between the full-resolution and the reduced-resolution.

For the IFD reduced-resolution subfiles linked to IFD0, IFDn_PixelScaleX and IFDn_PixelScaleY can be calculated like this:

[%unnumbered]
----
IFDn_PixelScaleX=IFD0_PixelScaleX*IFD0_ImageWidth/IFDn_ImageWidth
IFDn_PixelScaleY=IFD0_PixelScaleY*IFD0_ImageHeight/IFDn_ImageHeight
----

For a georeferenced file with a projected CRS that is fully defined in the EPSG database
there is no need to define the base Geographic CRS, geodetic datum, etc. in the TIFF file.
In these cases, the following keys in the IFD0 are sufficient;

[%unnumbered]
----
ImageWidth = 20111
ImageHeight = 16882
ModelTiepointTag = (0 0 0 187334 3255440 0)
ModelPixelScaleTag = (30 30 0)
GeoKeyDirectoryTag:
-    GTModelTypeGeoKey = 1 (ModelTypeProjected 2D)
-    GTRasterTypeGeoKey = 1 (RasterPixelIsArea)
-    ProjectedCRSGeoKey = 32628 (Projected 2D CRS WGS 84 / UTM zone 28N)
----

This example corresponds to imagery over the Canary Islands with a resolution
of 30 meters per pixel.
There is a grid intersection line in the image at pixel location (0, 0)

The 2 first numbers in ModelTiepointTag correspond to
the projected coordinate reference system easting/northing of (X:187334, Y:3255440)
(the numbers 4th and 5th in ModelTiepointTag) in the EPSG:32628 (WGS 84 / UTM zone 28N)

The georeference of the reduced-resolution subfiles (a.k.a IFDs whose bit 0 of the value of the NewSubfileType tag is set)
that are linked to this IFD0 are supposed to be the same except `ModelPixelScaleTag`
represents meters per pixel (pixel size).
In this example, IFD0 has `ImageWidth=20111` and `ImageHeigth=16882` while IFD1 has `ImageWidth=10056` and `ImageHeigth=8441`, so
`IFD1_PixelScaleX` and `IFD1_PixelScaleY` can be calculated as:
30*20111/10056=59.997 and 30*16882/8441=60.

As we can see in the example, tiles can easily result in non-square-pixels; a situation that should be handled by clients combining the data with other imagery that have square pixels.

[[optimized_geotiff-requirements-class]]
=== Requirement Class Optimized GeoTIFF

include::requirements/requirements_optimized_geotiff.adoc[]

In the <<geotiff-overviews-requirements-class>> requirement class, there is no guidance on how many reduced resolution subfiles a given COG should have. In a TIFF file with a big image, a COG with zero or one overview, can be rendered on a web client but it could be too slow to process and show in a client app. This requirement class provides more restrictions on how the COG should be build to accelerate visualization in web clients. It also adds the need for GeoTIFF as a dependency to <<geotiff-keys-requirements-class>>. The implementation of this conformance class and its dependencies generates what has been commonly called COG. 

==== Requirement Small Tiles

For optimized visualization, tiles should be small in their number of pixels, ideally a number smaller than the common number of pixels of a screen view port.

include::requirements/optimized_geotiff/small_tiles.adoc[]

==== Requirement Reduced-Resolution Subfiles Number

The number of reduced resolution subfiles is defined as a function of the number of pixels of the original image by creating progressive reduced resolution subfiles with less tiles until the number of tiles very small.  

include::requirements/optimized_geotiff/number.adoc[]

It is a common practice for visualization purposes that pixel sizes are generated as a power of 2. By selecting the number columns and rows of the original image also as a power of 2, each reduced resolution subfile can be generated from the previous smaller resolution by averaging the values of 4 contiguous pixels in one of the new subfile.

include::recommendations/optimized_geotiff/size_and_number.adoc[]

==== Requirement GeoTIFF

The geospatial reference is necessary for optimized visualization with other geospatial data.  

include::requirements/optimized_geotiff/geotiff.adoc[]
