[[HTTPRangeSupportRequirements]]
== HTTP range support requirements
HTTP Version 1.1 introduced a range header in the GET requests that supports requesting only a fragment of a resource.
If the server advertises "Accept-Ranges: bytes" in its response headers of a HEAD or GET request, the server is telling the client that bytes of data can be requested in parts, in separated requests.
The client can request just the bytes that it needs from the server at any time. In a web environment, this is very useful for serving files such as video. By using range requests, clients do not need to download the entire file to begin playing it.
In the case of COG, HTTP range is useful to get only the tiles needed to be processed or shown. This is done by getting the headers and IFDs of the TIFF file first and using this information to determine the conversion between tile indices to byte ranges containing the needed tiles.
A client trying to show a COG file on the screen can request the resolutions needed and only the tiles needed to cover the screen. Once the user moves or pans, other GET range requests will get the new needed resolutions and tiles.

[[http-range-requirements-class]]
=== Requirement Class HTTP range

include::requirements/requirements_httprange.adoc[]

==== Requirement range

include::requirements/httprange/httprange.adoc[]

The use of range in web browsers using HTTPS is restricted by the Cross-Origin Resource Sharing (CORS) rules (read more about this here: https://support.streamroot.io/hc/en-us/articles/115003168773-Range-request-basics). If the client and the server are in different domains (e.g., by using a generic COG-enabled web map client requesting COG files in a Amazon Cloud bucket) servers have to explicitly declare
that they allow the "range" header from a client that is not in the same domain.
Since this is a very common use case in geospatial data sharing
the decision was to make this a requirement.

include::requirements/httprange/httpsrange.adoc[]

NOTE: Support for range in HTTPS is necessary but not sufficient. It is not the purpose of this standard to specify how CORS is supported and that may change as web browsers and servers become more concerned about security.
However, it is worth notice that a server that wants to authorize a client application from another domain
(under the CORS rules) should also use the `Access-Control-Allow-Origin:` header
to list what domains are authorized to read the COG file
(or use `* to indicate that all domains are authorized).
Services that want to comply about the open data sharing principles should be willing to allow all clients reading the data even if they are in other domains.
However, this is up to the server implementers.
