== Conformance
This Standard defines 4 conformance classes.

*<<GeoTIFFFormatRequirements>>* (http://www.opengis.net/spec/COG/1.0/req/req-class-geotiff-format)

Defines what characteristics of the TIFF (or BigTIFF) format should be used. Target: TIFF Encoders (and COG clients)

*<<GeoTIFFOverviewsRequirements>>* (http://www.opengis.net/spec/COG/1.0/req/req-class-geotiff-overviews)

Defines the overview characteristics of the TIFF (or BigTIFF) format that should be used. Target: TIFF Encoders (and COG clients)

*<<HTTPRangeSupportRequirements>>* (http://www.opengis.net/spec/COG/1.0/req/req-class-http-range)

Defines how to use COG in the web to download only a fragment of the data. Target: A web Server (and COG web clients)

*<<GeoTIFFKeysRequirements>>* http://www.opengis.net/spec/COG/1.0/req/req-class-geotiff-keys

Defines how to GeoKeys to georeference the data. Target: GeoTIFF encoders

Conformance with this Standard shall be checked using all the relevant tests specified in Annex A (normative) of this document. The framework, concepts, and methodology for testing, and the criteria to be achieved to claim conformance are specified in the OGC Compliance Testing Policies and Procedures and the OGC Compliance Testing web site.

In order to conform to this OGC Standard, a software implementation shall choose to implement:
* Any one or more of the conformance levels specified in Annex A (normative).

All requirements-classes and conformance-classes described in this document are owned by the Standard(s) identified.

NOTE: Currently there is no way to list the conformance classes that a GeoTIFF file conforms so the COG is not specifying how to do so.
